<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate the table first
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Property::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $properties = [
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 3, // John Realtor
                'title' => 'Luxury 5 Bedroom Duplex in Victoria Island',
                'slug' => 'luxury-5-bedroom-duplex-victoria-island',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 150000000.00,
                'bedrooms' => 5,
                'bathrooms' => 6,
                'size' => 450.00,
                'size_unit' => 'sqm',
                'description' => 'Stunning luxury duplex in the heart of Victoria Island. This magnificent property features 5 spacious bedrooms, 6 modern bathrooms, a state-of-the-art kitchen, private swimming pool, and a 2-car garage. Perfect for families seeking upscale living in Lagos\' most prestigious neighborhood.',
                'address' => '15 Adeola Odeku Street',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101001',
                'latitude' => 6.4281,
                'longitude' => 3.4219,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Swimming Pool',
                    'Gym',
                    'BQ',
                    'Ample Parking',
                    'Security',
                    'Generator',
                    'Air Conditioning',
                    'Fitted Kitchen',
                    'Garden',
                    'Study Room',
                ],
                'metadata' => [
                    'year_built' => 2022,
                    'parking_spaces' => 2,
                    'floor_number' => null,
                    'total_floors' => 2,
                ],
                'views' => 245,
                'published_at' => now()->subDays(10),
                'created_at' => now()->subDays(10),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 5, // Sarah Johnson
                'title' => '3 Bedroom Apartment for Rent in Lekki Phase 1',
                'slug' => '3-bedroom-apartment-rent-lekki-phase-1',
                'type' => 'apartment',
                'listing_type' => 'rent',
                'price' => 2500000.00,
                'bedrooms' => 3,
                'bathrooms' => 4,
                'size' => 180.00,
                'size_unit' => 'sqm',
                'description' => 'Beautiful 3-bedroom apartment in a serene gated estate in Lekki Phase 1. Features modern finishes, spacious living areas, and access to estate amenities including swimming pool and gym. Annual rent.',
                'address' => '42 Admiralty Way',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101245',
                'latitude' => 6.4406,
                'longitude' => 3.4497,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Swimming Pool',
                    'Gym',
                    '24/7 Security',
                    'Power Supply',
                    'Water Supply',
                    'Parking Space',
                    'Children\'s Play Area',
                    'Air Conditioning',
                ],
                'metadata' => [
                    'year_built' => 2021,
                    'parking_spaces' => 2,
                    'floor_number' => 3,
                    'total_floors' => 5,
                    'service_charge' => 500000,
                ],
                'views' => 189,
                'published_at' => now()->subDays(5),
                'created_at' => now()->subDays(5),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 3,
                'title' => 'Prime Commercial Space in Victoria Island',
                'slug' => 'prime-commercial-space-victoria-island',
                'type' => 'commercial',
                'listing_type' => 'rent',
                'price' => 8000000.00,
                'bedrooms' => null,
                'bathrooms' => 4,
                'size' => 350.00,
                'size_unit' => 'sqm',
                'description' => 'Premium commercial office space in the business hub of Victoria Island. Ideal for corporate headquarters, tech companies, or professional services. Features include modern elevator, backup power, ample parking, and professional security.',
                'address' => '234 Ahmadu Bello Way',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101001',
                'latitude' => 6.4294,
                'longitude' => 3.4268,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Elevator',
                    'Generator',
                    'Parking',
                    '24/7 Security',
                    'Reception Area',
                    'Conference Rooms',
                    'Pantry',
                    'High-Speed Internet',
                    'Central AC',
                ],
                'metadata' => [
                    'year_built' => 2020,
                    'parking_spaces' => 10,
                    'floor_number' => 4,
                    'total_floors' => 8,
                ],
                'views' => 312,
                'published_at' => now()->subDays(15),
                'created_at' => now()->subDays(15),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 3,
                'created_by' => 5,
                'title' => 'Waterfront 4 Bedroom Terrace in Ikoyi',
                'slug' => 'waterfront-4-bedroom-terrace-ikoyi',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 95000000.00,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'size' => 320.00,
                'size_unit' => 'sqm',
                'description' => 'Exclusive waterfront terrace duplex in upscale Ikoyi. Enjoy breathtaking views of the lagoon while experiencing luxury living at its finest. Perfect blend of comfort and sophistication.',
                'address' => '18 Gerrard Road',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101233',
                'latitude' => 6.4582,
                'longitude' => 3.4319,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Waterfront',
                    'BQ',
                    'Terrace',
                    'Swimming Pool',
                    'Garden',
                    'Security',
                    'Generator',
                    'Parking',
                    'Study',
                ],
                'metadata' => [
                    'year_built' => 2023,
                    'parking_spaces' => 3,
                    'floor_number' => null,
                    'total_floors' => 2,
                ],
                'views' => 421,
                'published_at' => now()->subDays(20),
                'created_at' => now()->subDays(20),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 3,
                'title' => 'Shortlet: 2 Bedroom Serviced Apartment in Lekki',
                'slug' => 'shortlet-2-bedroom-serviced-apartment-lekki',
                'type' => 'shortlet',
                'listing_type' => 'rent',
                'price' => 35000.00,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'size' => 120.00,
                'size_unit' => 'sqm',
                'description' => 'Fully furnished and serviced 2-bedroom apartment available for short stays. Perfect for business travelers or visitors to Lagos. Rate shown is per night. Weekly and monthly rates available.',
                'address' => '67 Freedom Way',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101245',
                'latitude' => 6.4401,
                'longitude' => 3.4532,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'Fully Furnished',
                    'WiFi',
                    'DSTV',
                    'Kitchen',
                    'AC',
                    'Security',
                    'Power',
                    'Water',
                    'Parking',
                ],
                'metadata' => [
                    'year_built' => 2022,
                    'parking_spaces' => 1,
                    'floor_number' => 2,
                    'total_floors' => 4,
                    'minimum_stay_days' => 1,
                    'weekly_rate' => 200000,
                    'monthly_rate' => 700000,
                ],
                'views' => 156,
                'published_at' => now()->subDays(3),
                'created_at' => now()->subDays(3),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 5,
                'title' => '500sqm Land for Sale in Ajah',
                'slug' => '500sqm-land-for-sale-ajah',
                'type' => 'land',
                'listing_type' => 'sale',
                'price' => 35000000.00,
                'bedrooms' => null,
                'bathrooms' => null,
                'size' => 500.00,
                'size_unit' => 'sqm',
                'description' => 'Well located plot of land in rapidly developing Ajah area. Perfect for residential or commercial development. Clear title, good access road, and essential utilities available.',
                'address' => 'Lakowe Lakes Golf Estate',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101245',
                'latitude' => 6.4619,
                'longitude' => 3.6322,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'Good Title',
                    'Fenced',
                    'Gated Estate',
                    'Security',
                    'Good Road Access',
                    'Dry Land',
                    'Electricity',
                    'Water',
                ],
                'metadata' => [
                    'title_type' => 'Certificate of Occupancy',
                    'topography' => 'flat',
                ],
                'views' => 98,
                'published_at' => now()->subDays(7),
                'created_at' => now()->subDays(7),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 3,
                'title' => 'Brand New 4 Bedroom Semi-Detached Duplex in Ikeja',
                'slug' => 'brand-new-4-bedroom-semi-detached-duplex-ikeja',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 75000000.00,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'size' => 280.00,
                'size_unit' => 'sqm',
                'description' => 'Brand new semi-detached duplex in a well-planned estate in Ikeja GRA. Modern architecture, quality finishes, and strategic location close to major amenities.',
                'address' => '12 Oduduwa Crescent',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '100271',
                'latitude' => 6.5964,
                'longitude' => 3.3623,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'BQ',
                    'All Rooms Ensuite',
                    'Fitted Kitchen',
                    'Family Lounge',
                    'Parking',
                    'Security',
                    'Generator',
                    'Interlocked Compound',
                ],
                'metadata' => [
                    'year_built' => 2024,
                    'parking_spaces' => 3,
                    'floor_number' => null,
                    'total_floors' => 2,
                ],
                'views' => 167,
                'published_at' => now()->subDays(12),
                'created_at' => now()->subDays(12),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 5,
                'title' => 'Luxury Penthouse in Eko Atlantic',
                'slug' => 'luxury-penthouse-eko-atlantic',
                'type' => 'apartment',
                'listing_type' => 'sale',
                'price' => 280000000.00,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'size' => 420.00,
                'size_unit' => 'sqm',
                'description' => 'Ultra-luxury penthouse in prestigious Eko Atlantic City. Panoramic ocean views, world-class amenities, and unparalleled sophistication. The epitome of modern luxury living in Africa.',
                'address' => '5 Eko Atlantic Boulevard',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101001',
                'latitude' => 6.4126,
                'longitude' => 3.4039,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Ocean View',
                    'Private Elevator',
                    'Smart Home System',
                    'Infinity Pool',
                    'Gym',
                    'Concierge',
                    'Parking',
                    'Security',
                    'Cinema Room',
                    'Wine Cellar',
                ],
                'metadata' => [
                    'year_built' => 2023,
                    'parking_spaces' => 4,
                    'floor_number' => 15,
                    'total_floors' => 15,
                    'service_charge' => 5000000,
                ],
                'views' => 589,
                'published_at' => now()->subDays(25),
                'created_at' => now()->subDays(25),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 3,
                'created_by' => 3,
                'title' => '1 Bedroom Studio Apartment in Yaba',
                'slug' => '1-bedroom-studio-apartment-yaba',
                'type' => 'apartment',
                'listing_type' => 'rent',
                'price' => 800000.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'size' => 45.00,
                'size_unit' => 'sqm',
                'description' => 'Compact and modern studio apartment perfect for young professionals or students. Located in vibrant Yaba, close to tech hubs and universities. Annual rent.',
                'address' => '89 Herbert Macaulay Way',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101212',
                'latitude' => 6.5104,
                'longitude' => 3.3711,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'Kitchenette',
                    'AC',
                    'Security',
                    'Water',
                    'Power Backup',
                    'Internet Ready',
                ],
                'metadata' => [
                    'year_built' => 2021,
                    'parking_spaces' => 1,
                    'floor_number' => 1,
                    'total_floors' => 3,
                ],
                'views' => 76,
                'published_at' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 5,
                'title' => '6 Bedroom Mansion in Banana Island',
                'slug' => '6-bedroom-mansion-banana-island',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 450000000.00,
                'bedrooms' => 6,
                'bathrooms' => 8,
                'size' => 750.00,
                'size_unit' => 'sqm',
                'description' => 'Magnificent mansion on Nigeria\'s most exclusive island. Ultimate luxury with every conceivable amenity. Private cinema, spa, wine cellar, and staff quarters. For the discerning few.',
                'address' => '23 Banana Island Road',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101001',
                'latitude' => 6.4167,
                'longitude' => 3.4313,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Waterfront',
                    'Private Jetty',
                    'Swimming Pool',
                    'Tennis Court',
                    'Cinema',
                    'Spa',
                    'Gym',
                    'Wine Cellar',
                    'Staff Quarters',
                    'Smart Home',
                    'Garage for 6 cars',
                ],
                'metadata' => [
                    'year_built' => 2023,
                    'parking_spaces' => 6,
                    'floor_number' => null,
                    'total_floors' => 3,
                ],
                'views' => 734,
                'published_at' => now()->subDays(30),
                'created_at' => now()->subDays(30),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 3,
                'title' => 'Warehouse Space in Apapa',
                'slug' => 'warehouse-space-apapa',
                'type' => 'commercial',
                'listing_type' => 'rent',
                'price' => 12000000.00,
                'bedrooms' => null,
                'bathrooms' => 2,
                'size' => 1200.00,
                'size_unit' => 'sqm',
                'description' => 'Large warehouse facility in strategic Apapa location. Excellent for logistics, storage, or light manufacturing. High ceiling, good access, and proximity to ports.',
                'address' => '156 Apapa-Oshodi Expressway',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '102273',
                'latitude' => 6.4481,
                'longitude' => 3.3594,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'Loading Bay',
                    'High Ceiling',
                    'Office Space',
                    'Security',
                    'Parking',
                    '3-Phase Power',
                    'Water Supply',
                    'Fire Safety Systems',
                ],
                'metadata' => [
                    'year_built' => 2018,
                    'parking_spaces' => 20,
                    'floor_number' => null,
                    'total_floors' => 1,
                    'ceiling_height' => 8,
                ],
                'views' => 134,
                'published_at' => now()->subDays(8),
                'created_at' => now()->subDays(8),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 5,
                'title' => '3 Bedroom Bungalow in Magodo',
                'slug' => '3-bedroom-bungalow-magodo',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 45000000.00,
                'bedrooms' => 3,
                'bathrooms' => 4,
                'size' => 200.00,
                'size_unit' => 'sqm',
                'description' => 'Charming detached bungalow in peaceful Magodo Phase 2. Perfect for families seeking single-level living. Well maintained with beautiful landscaping.',
                'address' => '34 CMD Road, Magodo Phase 2',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '100218',
                'latitude' => 6.5833,
                'longitude' => 3.3722,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'BQ',
                    'Garden',
                    'Parking',
                    'Security',
                    'All Rooms Ensuite',
                    'Pop Ceiling',
                    'Tiled Floor',
                    'Fitted Kitchen',
                ],
                'metadata' => [
                    'year_built' => 2019,
                    'parking_spaces' => 3,
                    'floor_number' => null,
                    'total_floors' => 1,
                ],
                'views' => 142,
                'published_at' => now()->subDays(14),
                'created_at' => now()->subDays(14),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 3,
                'created_by' => 3,
                'title' => 'Luxury 2 Bedroom Apartment in Parkview Estate',
                'slug' => 'luxury-2-bedroom-apartment-parkview-estate',
                'type' => 'apartment',
                'listing_type' => 'rent',
                'price' => 3500000.00,
                'bedrooms' => 2,
                'bathrooms' => 3,
                'size' => 150.00,
                'size_unit' => 'sqm',
                'description' => 'Exquisite 2-bedroom apartment in the prestigious Parkview Estate, Ikoyi. Top-tier finishes, 24/7 security, and access to world-class amenities. Annual rent.',
                'address' => '8 Parkview Estate',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101233',
                'latitude' => 6.4547,
                'longitude' => 3.4259,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'Clubhouse',
                    'Swimming Pool',
                    'Gym',
                    'Tennis Court',
                    'Security',
                    'Power',
                    'Parking',
                    'Garden',
                    'Children\'s Play Area',
                ],
                'metadata' => [
                    'year_built' => 2022,
                    'parking_spaces' => 2,
                    'floor_number' => 4,
                    'total_floors' => 6,
                    'service_charge' => 1200000,
                ],
                'views' => 298,
                'published_at' => now()->subDays(6),
                'created_at' => now()->subDays(6),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 1,
                'created_by' => 5,
                'title' => 'Mixed-Use Development in Surulere',
                'slug' => 'mixed-use-development-surulere',
                'type' => 'commercial',
                'listing_type' => 'sale',
                'price' => 180000000.00,
                'bedrooms' => null,
                'bathrooms' => 8,
                'size' => 600.00,
                'size_unit' => 'sqm',
                'description' => 'Prime mixed-use property with commercial spaces on ground floor and residential apartments above. Excellent investment opportunity in bustling Surulere. Fully tenanted with strong rental yield.',
                'address' => '45 Bode Thomas Street',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101283',
                'latitude' => 6.4989,
                'longitude' => 3.3536,
                'status' => 'available',
                'is_featured' => false,
                'features' => [
                    'Ground Floor Retail',
                    'Residential Apartments',
                    'Parking',
                    'Generator',
                    'Water Supply',
                    'Security',
                    'High ROI',
                    'Fully Tenanted',
                ],
                'metadata' => [
                    'year_built' => 2017,
                    'parking_spaces' => 8,
                    'floor_number' => null,
                    'total_floors' => 3,
                    'annual_rental_income' => 24000000,
                ],
                'views' => 203,
                'published_at' => now()->subDays(18),
                'created_at' => now()->subDays(18),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'branch_id' => 2,
                'created_by' => 3,
                'title' => '5 Bedroom Fully Detached House in Chevron',
                'slug' => '5-bedroom-fully-detached-house-chevron',
                'type' => 'house',
                'listing_type' => 'sale',
                'price' => 120000000.00,
                'bedrooms' => 5,
                'bathrooms' => 6,
                'size' => 400.00,
                'size_unit' => 'sqm',
                'description' => 'Spacious fully detached duplex in the heart of Chevron, Lekki. Ideal family home in a serene and secure environment. Close to schools, shopping, and entertainment.',
                'address' => '16 Chevron Drive',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'zip_code' => '101245',
                'latitude' => 6.4321,
                'longitude' => 3.5067,
                'status' => 'available',
                'is_featured' => true,
                'features' => [
                    'BQ',
                    'Swimming Pool',
                    'All Rooms Ensuite',
                    'Fitted Kitchen',
                    'Family Lounge',
                    'Study',
                    'Parking',
                    'Security',
                    'Generator',
                    'Landscaped Garden',
                ],
                'metadata' => [
                    'year_built' => 2021,
                    'parking_spaces' => 4,
                    'floor_number' => null,
                    'total_floors' => 2,
                ],
                'views' => 367,
                'published_at' => now()->subDays(9),
                'created_at' => now()->subDays(9),
                'updated_at' => now(),
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }

        $this->command->info('Properties seeded successfully!');
        $this->command->info('Created 15 properties for Prime Realty (tenant_id: 1)');
    }
}
